#!/bin/sh -x

echo
echo Changes should be made to FAQ.tt *not* FAQ.pm
echo

echo
echo I hope you bumped the version number
echo

hg commit -m "`grep 'VERSION =' FAQ.tt`"
hg push

# make manifest

./tt.pl FAQ.tt
mv FAQ.tt-out FAQ.pm
pod2html FAQ.pm > FAQ.html
perl Makefile.PL
rm *.tar.gz
make tardist


