#!/bin/sh -x

#!/bin/sh -x

echo
echo Changes should be made to FAQ.tt *not* FAQ.pm
echo

echo
echo I hope you bumped the version number
echo

#cp ~/bin/tt.pl .
./tt.pl FAQ.tt
mv FAQ.tt-out FAQ.pm
pod2html FAQ.pm > FAQ.html
perl Makefile.PL PREFIX=$PERL
rm *.tar.gz
make tardist


