#!/bin/sh

#!/bin/sh -x

echo
echo Changes should be made to *FAQ.tt* not FAQ.pm
echo

echo
echo I hope you bumped the version number
echo

cp ~/bin/tt.pl .
~/bin/tt.pl FAQ.tt
mv FAQ.tt-out FAQ.pm
perl Makefile.PL PREFIX=$PREFIX
rm *.tar.gz
make tardist




